#! /bin/sh
# Set colors

#bspc config focused_border_color "#1793D0"
bspc config focused_border_color "#000000"
bspc config normal_border_color "#001A1A"
bspc config active_border_color "#1F2B2B"
bspc config presel_border_color "#2A4E5A"
bspc config urgent_border_color "#ZA4E5A"

bspc config border_width        2
bspc config window_gap		15
bspc config top_padding		15
bspc config left_padding	0
bspc config right_padding	0
bspc config bottom_padding	0

#bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#bspc rule -a * floating=on

#bspc monitor VGA1 -d one

bspc monitor -d • • • • • • • •
bspc monitor DP2  -d •

polybar bar-top &
sxhkd &

