#! /bin/sh

# Start the panel
#~/git/fonts/install &
#~/.config/bspwm/panel &
sxhkd -c ~/.config/sxkhd/sxhkdrc &
sakura &
#panel &
conky &
dzen2 &

# Set background
feh --bg-fill ~/.wallpaper/wall.jpg &


# Set colors
bspc config focused_border_color "#1793D0"
bspc config normal_border_color "#4C4C4C"
bspc config active_border_color "#CEE318"
bspc config presel_border_color "#79CDCD"
bspc config urgent_border_color "#79CDCD"


bspc config border_width        	 2
bspc config window_gap          	 8
bspc config top_padding 		 15
bspc config focused_border_color	 #D1A747

bspc config split_ratio          	 0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle      	 true
bspc config focus_by_distance  		 true
bspc config focus_follows_pointer	 true

bspc config remove_disabled_monitors 	 true
bspc config remove_unplugged_monitors 	 true

bspc monitor DVI-I-1 -d I II III IV
bspc monitor DVI-I-2 -d V VI VII
bspc monitor DP-1 -d VIII IX X

# Rules
# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a	geary		desktop=^9 	follow=on
bspc rule -a 	vlc		floating=on
#bspc rule -a 	Kupfer.py 	focus=on
#bspc rule -a 	Screenkey 	manage=off
#bspc rule -a 	steam 		floating=on
#bspc rule -a 	gajim 		floating=on
#bspc rule -a 	thunar		floating=on
#bspc rule -a 	wimp		floating=on
#bspc rule -a 	android-studi	floating=on
#bspc rule -a 	eclpse 		floating=on
#bspc rule -a 	primusrun	floating=on

# Autostarts
#sakura -e weechat &
#urxvt -e profanity &
#stalonetray &
#touchegg	&
#nm-applet 	&
#owncloud 	&
#gajim 		&
#caffeine	&
#wmname LG3D	&
#gvolicon	&

#Enable the auto brightness
#als-controller -e &
