#!/bin/sh

RED="\\033[1;31m"
GREEN="\\033[1;32m"
BOLD="\\033[1m"
RESET="\\033[0m"

function usage()
{
    echo "Usage: makedepo \"RepoName\" [names of mates ...]"
    exit 1
}

args=( "$@" )

if [ $args ]
then
    echo -e "Creating $args repository ..."
    blih -u $LOGIN repository create ${args[0]}
    echo -e "Set right for ramassage-tek ..."
    blih -u $LOGIN repository setacl ${args[0]} ramassage-tek +r
    for ((i = 1 ; i < ${#args[@]} ; i=$i+1));
    do
	echo "Setting right for ${args[$i]} on ${args[0]} ..."
	blih -u $LOGIN repository setacl ${args[0]} ${args[$i]} +rw
    done
    git clone giard_b@git.epitech.eu:/giard_b/${args[0]}
else
    usage
fi
